#!/bin/sh

### BEGIN INIT INFO
# Provides:          spawn-fcgi-mercurial
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts FastCGI for mercurial
# Description:       starts FastCGI for mercurial using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=spawn-fcgi-mercurial
PID=/var/run/spawn-fcgi-mercurial.pid
DAEMON=/usr/bin/spawn-fcgi
DAEMON_OPTS="-f /home/mercurial/hgweb.fcgi -a 127.0.0.1 -p 9000 -u mercurial -g mercurial -P $PID"

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
        if [ -f $PID ]
        then
            echo the process is already running
            exit 1
        fi
        echo "Starting $NAME: "
        start-stop-daemon --start --pidfile $PID --exec $DAEMON -- $DAEMON_OPTS
        echo "done."
        ;;
  stop)
        echo "Stopping $NAME: "
        start-stop-daemon --stop  --pidfile $PID --retry 5
        rm -f $PID
        echo "done."
        ;;
  restart)
        echo "Stopping $NAME: "
        start-stop-daemon --stop  --pidfile $PID --retry 5
        rm -f $PID
        echo "done..."
        sleep 1
        echo "Starting $NAME: "
        start-stop-daemon --start --pidfile $PID --exec $DAEMON -- $DAEMON_OPTS
        echo "done."
        ;;
  *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
